### ISSUE TITLE
after upgrading to 1.6 we are getting type script errors in our code

### ISSUE THREAD

**Issue by sivanisentinel** [DevExpress/testcafe#4444]
After the upgrade, for every test with a before function we get this TS error:
Property 'before' does not exist on type 'It'
How do I resolve this? do you have breaking changes?

**Comment by AlexKamaev** [comment]
We have recently published the 1.6.1 version, which contains some fixes for the typescript. Could you please upgrade to this version?

If the issue stills persists after the upgrade, please share your project with us or create a sample, which demonstrates the iss

**Comment by sivanisentinel** [comment]
fixed! thanks!
