### ISSUE TITLE
Getting (node:19069) UnhandledPromiseRejectionWarning after upgrading to 0.17.2

### ISSUE THREAD

**Issue by planet71** [DevExpress/testcafe#1769]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Unable to run tests. After upgrading to v0.17.2 and running:

`testcafe chrome test1.js --no-sandbox`

I get the following error:

`(node:19069) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module 'testcafe-hammerhead'`

`(node:19069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the No
de.js process with a non-zero exit code.`

### What is the expected behavior?

Tests should run successfully.

### How would you reproduce the current behavior (if this is a bug)?

Run tests.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Tested on localhost.

Test code

```js
import { Selector, Role, ClientFunction } from 'testcafe';

const messengerBody = Selector('div').withAttribute('data-test', 'container');

const user = Role('http://localhost:8091', async t => {
    await t
        .typeText('#user', 'someid')
        .typeText('#pass', 'someuserpass')
        .click('#btn');

});

fixture `Login`
    .page('http://localhost:8091');


test('check if feature is loaded', async t => {
    await t
        .useRole(user)
        .expect(messengerBody.exists).ok();
});
```

### Specify your

* operating system: Ubuntu 16.04 LTS
* testcafe version: 0.17.2
* node.js version: 8.2.1

**Comment by AlexanderMoskovkin** [comment]
Hi @planet71,

Have you installed testcafe locally into your project or globally (with the `-g` npm flag)? If locally could you please try to remote the `node_modules` directory and reinstall all dependencies again?

**Comment by planet71** [comment]
Hi @AlexanderMoskovkin,
I've removed `node_modules` and  reintsalled all dependencies, but it didn't help out.

**Comment by AlexanderMoskovkin** [comment]
what do you use, npm or yarn?

**Comment by AndreyBelym** [comment]
Hello @planet71, I encountered similar type of issue, but not with version `0.17.2`. If you are using npm, try to clean cache `npm cache clean -f`, remove `node_modules` and install TestCafe. If it won't help, try to install `npm@4.x.x`.

**Comment by planet71** [comment]
Cleaning cache helped out. Thanks. 

@AlexanderEgorov @AndreyBelym
