### ISSUE TITLE
open browser after compile success

### ISSUE THREAD

**Issue by link89** [DevExpress/testcafe#3219]
### What is your Test Scenario?

Using testcafe to run hundreds of tests on selenium-grid

### What is the Current behavior?

selenium webdriver throw Timeout when cases compile didn't finish with BrowsersTimeout.
The reason for this error is clear. We are running our cases on selenium-grid for a long time. After upgrade to 0.23.x, we found that testcafe try to open browsers before cases compile. We will start a async task to sending heartbeats to selenium-grid to keep browsers open. But compile cases will block this tasks. It's ok when little files to compile, but it become a problem when number of cases is large. I hope we should follow the logic of version previous 0.23, which will open browsers after compile.
 
### What is the Expected behavior?

 open browser after compile success

### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  0.23.2

**Comment by link89** [comment]
```typescript
    async createRunnableConfiguration () {
        const reporterPlugins = this._getReporterPlugins();

        // NOTE: If a user forgot to specify a browser, but has specified a path to tests, the specified path will be
        // considered as the browser argument, and the tests path argument will have the predefined default value.
        // It's very ambiguous for the user, who might be confused by compilation errors from an unexpected test.
        // So, we need to retrieve the browser aliases and paths before tests compilation.
        const browserInfo = await this._getBrowserInfo();

        if (this._canUseParallelBootstrapping(browserInfo))
            return { reporterPlugins, ...await this._bootstrapParallel(browserInfo) };

        return { reporterPlugins, ...await this._bootstrapSequence(browserInfo) };
    }
```
I have found following comment explain why you make this choice. I don't think it a good reason to do it this way since it will waste browser resources when you running testcafe in CI/CD pipeline.

**Comment by link89** [comment]
Here is the trouble maker and a simple fix: https://github.com/DevExpress/testcafe/pull/3221/files
