### ISSUE TITLE
After Update angular-oauth2-oidc from 8.0.4 to 9.0.1 we get exceptions in Testcafe

### ISSUE THREAD

**Issue by convexdezign** [DevExpress/testcafe#4849]
### Are you requesting a feature or reporting a bug?
Bug 

### What is your Test Scenario?
Updateting from OAuth 8.0.4 to 9.0.1

### What is the Current behavior?
An Error Occurs in Hammerhead when Testcafe tries to click a Button

### What is the Expected behavior?
Succefully clicked Button.

### How would you reproduce the current behavior (if this is a bug)?
Update OAuth to 9.0.1

### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    v12.13.1
* command-line arguments:  -s takeOnFails=true --debug-on-fail
* browser name and version: Chrome 80.0.3987.122 and Chrome:Headless 78.0.3904.97 / Linux 0.0
* platform and version:          Windows and Linux

Additional ErrorInfos:
hammerhead.js:6 Error in initAuthorizationCodeFlow
window.console.<computed> @ hammerhead.js:6
(anonymous) @ main.083f21dea3e042ccbffb.js:1768
(anonymous) @ main.083f21dea3e042ccbffb.js:437
t.invoke @ polyfills.123b6da12ffbf9c14a0b.js:9
onInvoke @ main.083f21dea3e042ccbffb.js:1271
t.invoke @ polyfills.123b6da12ffbf9c14a0b.js:9
e.run @ polyfills.123b6da12ffbf9c14a0b.js:9
(anonymous) @ polyfills.123b6da12ffbf9c14a0b.js:17
t.invokeTask @ polyfills.123b6da12ffbf9c14a0b.js:9
onInvokeTask @ main.083f21dea3e042ccbffb.js:1271
t.invokeTask @ polyfills.123b6da12ffbf9c14a0b.js:9
e.runTask @ polyfills.123b6da12ffbf9c14a0b.js:9
m @ polyfills.123b6da12ffbf9c14a0b.js:9
e.invokeTask @ polyfills.123b6da12ffbf9c14a0b.js:9
p @ polyfills.123b6da12ffbf9c14a0b.js:40
h @ polyfills.123b6da12ffbf9c14a0b.js:40
hammerhead.js:6 TypeError: Cannot read property 'digest' of undefined
    at e.<anonymous> (main.083f21dea3e042ccbffb.js:437)
    at main.083f21dea3e042ccbffb.js:1679
    at Object.next (main.083f21dea3e042ccbffb.js:1679)
    at main.083f21dea3e042ccbffb.js:1679
    at new t (polyfills.123b6da12ffbf9c14a0b.js:17)
    at c (main.083f21dea3e042ccbffb.js:1679)
    at e.calcHash (main.083f21dea3e042ccbffb.js:437)
    at t.<anonymous> (main.083f21dea3e042ccbffb.js:437)
    at main.083f21dea3e042ccbffb.js:1679
    at Object.next (main.083f21dea3e042ccbffb.js:1679)
    at a (main.083f21dea3e042ccbffb.js:1679)
    at t.invoke (polyfills.123b6da12ffbf9c14a0b.js:9)
    at Object.onInvoke (main.083f21dea3e042ccbffb.js:1271)
    at t.invoke (polyfills.123b6da12ffbf9c14a0b.js:9)
    at e.run (polyfills.123b6da12ffbf9c14a0b.js:9)
    at polyfills.123b6da12ffbf9c14a0b.js:17
    at t.invokeTask (polyfills.123b6da12ffbf9c14a0b.js:9)
    at Object.onInvokeTask (main.083f21dea3e042ccbffb.js:1271)
    at t.invokeTask (polyfills.123b6da12ffbf9c14a0b.js:9)
    at e.runTask (polyfills.123b6da12ffbf9c14a0b.js:9)
    at m (polyfills.123b6da12ffbf9c14a0b.js:9)
    at e.invokeTask [as invoke] (polyfills.123b6da12ffbf9c14a0b.js:9)
    at p (polyfills.123b6da12ffbf9c14a0b.js:40)
    at Animation.h (polyfills.123b6da12ffbf9c14a0b.js:40)
window.console.<computed> @ hammerhead.js:6
(anonymous) @ main.083f21dea3e042ccbffb.js:1768
(anonymous) @ main.083f21dea3e042ccbffb.js:437
t.invoke @ polyfills.123b6da12ffbf9c14a0b.js:9
onInvoke @ main.083f21dea3e042ccbffb.js:1271
t.invoke @ polyfills.123b6da12ffbf9c14a0b.js:9
e.run @ polyfills.123b6da12ffbf9c14a0b.js:9
(anonymous) @ polyfills.123b6da12ffbf9c14a0b.js:17
t.invokeTask @ polyfills.123b6da12ffbf9c14a0b.js:9
onInvokeTask @ main.083f21dea3e042ccbffb.js:1271
t.invokeTask @ polyfills.123b6da12ffbf9c14a0b.js:9
e.runTask @ polyfills.123b6da12ffbf9c14a0b.js:9
m @ polyfills.123b6da12ffbf9c14a0b.js:9
e.invokeTask @ polyfills.123b6da12ffbf9c14a0b.js:9
p @ polyfills.123b6da12ffbf9c14a0b.js:40
h @ polyfills.123b6da12ffbf9c14a0b.js:40
[](url)

**Comment by convexdezign** [comment]
![Anmerkung 2020-03-09 092846](https://user-images.githubusercontent.com/44361178/76195365-6a2f1980-61e8-11ea-9c5f-ea1fdb538608.png)

**Comment by Dmitry-Ostashev** [comment]
This information is insufficient to determine the cause of the issue. Could you please give us a public url or a sample project with a test so that we can reproduce this behavior on our side?
