### ISSUE TITLE
Testcafe doesn't work with node 18.0

### ISSUE THREAD

**Issue by mecciau** [DevExpress/testcafe#7000]
### What is your Scenario?

Fresh install of testcafe 1.18.6
trying to run a simple test with `npx testcafe`

```
fixture`Getting Started`.page`https://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    console.log('all good')
});
```

### What is the Current behavior?

```
% npx testcafe 

ERROR TypeError: details.family.toLowerCase is not a function
    at /Users/dominykasverkauskas/src/hello/node_modules/ip/lib/ip.js:385:39
    at Array.filter (<anonymous>)
    at /Users/dominykasverkauskas/src/hello/node_modules/ip/lib/ip.js:384:37
    at Array.map (<anonymous>)
    at ip.address (/Users/dominykasverkauskas/src/hello/node_modules/ip/lib/ip.js:379:37)
    at Proxy.getIPAddress (/Users/dominykasverkauskas/Shopify/hello/node_modules/endpoint-utils/index.js:109:15)
    at getValidHostname (/Users/dominykasverkauskas/hello/node_modules/testcafe/lib/index.js:26:34)
    at Object.createTestCafe [as default] (/Users/dominykasverkauskas/src/github.com/node_modules/testcafe/lib/index.js:71:9)
    at async runTests (/Users/dominykasverkauskas/src/hello/node_modules/testcafe/lib/cli/cli.js:63:22)
    at async cli (/Users/dominykasverkauskas/src/hello/node_modules/testcafe/lib/cli/cli.js:136:13)

Type "testcafe -h" for help.
```

### What is the Expected behavior?

To start running the test

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example

### What is your TestCafe test code?

spec file:

```
fixture`Getting Started`.page`https://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    console.log('all good')
});
```

### Your complete configuration file

```
module.exports = {
    browsers: 'chrome',
    src: "./tests"
}
```

### Steps to Reproduce

1. use node 18.0.0
2. fresh install testcafe
3. run any test

### TestCafe version

1.18.6

### Node.js version

18.0.0

### Command-line arguments

 testcafe chrome -e test.js

**Comment by miherlosev** [comment]
Hi @mecciau 

This error is caused by a breaking change in Node.js 18, which broke a lot of popular modules.
See these threads:
* https://github.com/indutny/node-ip/issues/113
* https://github.com/nodejs/node/pull/41431#pullrequestreview-929717323

This issue will be fixed in the latest version of Node.js or related modules.

**Comment by megaandros** [comment]
I can't run any test cafe test. How to be right now? Who has temporary solution? I'm not so good in JS to fix "ip.js" code.

**Comment by megaandros** [comment]
The issue can be fixed with node.js = v.17.9.0
How to downgrade - https://stackoverflow.com/questions/58280757/how-to-upgrade-node-to-specific-version-in-macos-mojave-and-update-the-active-p

**Comment by ND3V** [comment]
A note on this: starting tests via the VSCode plugin "Testcafe Test Runner" does work, 
so one might find a way around this.
