### ISSUE TITLE
Cannot assign withAttribute() result to SelectorPromise variable with 1.8.0

### ISSUE THREAD

**Issue by neekfenwick** [DevExpress/testcafe#4685]
### Are you requesting a feature or reporting a bug?
Bug (if it is a bug, perhaps a local config issue)

### What is your Test Scenario?
Assign the result of withAttribute() to a SelectorPromise variable, then use that variable.

### What is the Current behavior?
I get a compiler error when trying to assign withAttribute() result to a SelectorPromise typed variable on 1.8.0.  The same error does not come up if I inline the use of that SelectorPromise, or if I roll back to 1.6.1.

### What is the Expected behavior?
I'd expect to be able to do:
let sel:SelectorPromise = Selector('a').withAttribute('href', /foo=bar/);

### How would you reproduce the current behavior (if this is a bug)?
run the test script on the command line, I use:

./node_modules/.bin/testcafe chrome:headless selector_problem.ts 

#### Provide the test code and the tested page URL (if applicable)
Test Script selector-problem.ts:
```js
import { Selector } from 'testcafe';

fixture('Testing Begin...')
    .page(`https://www.google.com`);

test('selector-problem', async t => {

    let sel:SelectorPromise = Selector('a').withAttribute('href', /foo=bar/);
    if (await sel.exists) {
        console.log('ok');
    }
});
```

N/A
### Your Environment details:
 
* testcafe version:                   1.8.0 (but works with 1.6.1)
* node.js version:                    9.11.1
* command-line arguments:  ./node_modules/.bin/testcafe chrome:headless selector_problem.ts
* browser name and version: google-chrome-stable-79.0.3945.130-1.x86_64
* platform and version:          CentOS 7

We recently installed a new server and the `npm i` resulted in a newer version of testcafe to be installed (1.8.0) and our test script no longer compiles.

### Output on local machine using 1.6.1 ###

$ node -v
v9.11.1

$ ./node_modules/.bin/testcafe -v
1.6.1

$ ./node_modules/.bin/testcafe chrome:headless selector_problem.ts 
 Running tests in:
 - HeadlessChrome 66.0.3359 / Linux 0.0.0

 Testing Begin...
 ✓ selector-problem

 1 passed (6s)

### Output on production using 1.8.0 ###

```$ node -v
v9.11.1

$ ./node_modules/.bin/testcafe -v
1.8.0

$ ./node_modules/.bin/testcafe chrome:headless selector_problem.ts 
ERROR Cannot prepare tests due to an error.

Error: TypeScript compilation failed.
/redacted/selector_problem.ts (8, 31): Type 'Selector' is missing the following properties from type 'SelectorPromise': then, catch, [Symbol.toStringTag]

    at Function._reportErrors (/redacted/test/node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:79:15)
    at TypeScriptTestFileCompiler._compileFilesToCache (/redacted/test/node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:101:40)
    at TypeScriptTestFileCompiler._precompileCode (/redacted/test/node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:129:18)
    at TypeScriptTestFileCompiler._compileCodeForTestFiles (/redacted/test/node_modules/testcafe/src/compiler/test-file/api-based.js:111:29)
    at tsConfig.init.then (/redacted/test/node_modules/testcafe/src/compiler/test-file/formats/typescript/compiler.ts:85:30)

Type "testcafe -h" for help.
```

VSCode tooltip shows withAttribute() should return a SelectorPromise, so the assignment looks OK to me.

If I inline the use of the selector, it compiles fine, i.e.:

```js
    // let sel:SelectorPromise = Selector('a').withAttribute('href', /foo=bar/);
    if (await Selector('a').withAttribute('href', /foo=bar/).exists) {
        console.log('ok');
    }
```

If I roll back our production system to use 1.6.1 to match my local machine (by editing package.json to force it to use testcafe 1.6.1 ; rm -rf node_modules ; npm i) it compiles fine.

Am I just misunderstanding something basic about TypeScript typing?

**Comment by alexey-lin** [comment]
The `Selector.withAttribute` method returns a `Selector`, but in v1.6.1 it was declared as `SelectorPromise` in the TypeScript definitions by mistake (see [#4448](https://github.com/DevExpress/testcafe/issues/4448)). This error was fixed in v1.7.0.

I suggest you use the latest version of TestCafe both on your local machine and in the production system.
