### ISSUE TITLE
Firefox: browserClient.closeBrowserChildWindow is not a function 

### ISSUE THREAD

**Issue by florachen-okta** [DevExpress/testcafe#7285]
### What is your Scenario?

I have multiple windows running and test with Firefox browser.

### What is the Current behavior?

Testcafe throws
```
 Unhandled promise rejection:
      TypeError: browserClient.closeBrowserChildWindow is not a function
```

### What is the Expected behavior?

The error shouldn't be thrown. This used to work on v1.18, and if switch to chrome the test is passed.

### What is your public website URL? (or attach your complete example)

https://testcafe.io/

### What is your TestCafe test code?

```
fixture `Microsoft DevBlogs Login page`
    .page('https://devblogs.microsoft.com/');

test('should pass', async (t) => {
await t
    .click('.login-but') 
    .click('.nsl-button-google') 
    .closeWindow();
});
```

### Your complete test report

```✖ should pass  (7.97s)

   1) Unhandled promise rejection:
      
      TypeError: browserClient.closeBrowserChildWindow is not a function

      Browser: Firefox 104.0 / macOS 10.15
```

### Steps to Reproduce

1. Try the testcode
2. Run tests with firefox browser.

### TestCafe version

2.0.0

### Node.js version

v16.15.1

### Command-line arguments

testcafe firefox test.js

**Comment by miherlosev** [comment]
Hi @florachen-okta 

Thank you for the shared information. I've reproduced the issue.

**Comment by gamlerhart** [comment]
Note: We have the same issue with the rule, but the error shows up in the first test using the role.

Like:

Role(...,async (t) => {
   await operationsOpeningPopup().closeWindow() 
})

Then the first test using this role fails with this error:

```
   1) - Error in Role initializer -
      Unhandled promise rejection:
      
      TypeError: browserClient.closeBrowserChildWindow is not a function
      at BrowserProviderPluginHost.closeBrowserChildWindow
      (/home/roman/dev/include-cloud/node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:108:30)
      at BrowserProvider.closeBrowserChildWindow
      (/home/roman/dev/include-cloud/node_modules/testcafe/src/browser/provider/index.ts:444:27)
      at _onCloseWindowRequest
      (/home/roman/dev/include-cloud/node_module
```

Follow up tests do work.

**Comment by Aleksey28** [comment]
Hi @gamlerhart,

Thank you for sharing the example. The issue is reproduced in any part of a test.

**Comment by thomaswong79** [comment]
I'm running into the same issue as well. Turns out to be only happening on firefox, not chrome.

**Comment by amiablea2** [comment]
- Fails for **Chrome 102** as well:
- testcafe: "**2.1.0**",

```
Unhandled promise rejection:
    TypeError: browserClient.closeBrowserChildWindow is not a function
   at BrowserProviderPluginHost.closeBrowserChildWindow (.../node_modules/testcafe/src/browser/provider/built-in/dedicated/base.js:108:30)
```

**Comment by exommlr** [comment]
@AlexKamaev is this something that has been introduced for #6037?

**Comment by AlexKamaev** [comment]
@exommlr
Yes, I've checked it. We changed the priority of this issue, so we will discuss it in the near future.

**Comment by exommlr** [comment]
@AlexKamaev thank you very much for fixing this!
