### ISSUE TITLE
TestCafe runner.video is not a function at createTestCafe.then.testcafe

### ISSUE THREAD

**Issue by Esteban26** [DevExpress/testcafe#3676]
Hi, I'm creating this issue since I'm facing an issue while trying to create test videos using the TestCase Javascript API.

I'm working with testcafe version 0.22.0 and I already have the prerequisites you request in your documentation.

I already have installed the dmg file ffmpeg in my computer and also I already installed this library "@ffmpeg-installer/ffmpeg": "^1.0.17" with npm

My OS is MacOSX HighSierra

https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/screenshots-and-videos.html#record-videos

And basically the issue is video function doesn't exist in my runner object.

`createTestCafe('localhost', 1337, 1338)
    .then(testcafe => {
        runner = testcafe.createRunner();

        console.log(runner.video);

        return runner
        .video(artifactsPath)
        .src(specsPath + '/run-animation.spec.ts')
        .browsers(['chrome'])
        .reporter('json')
        .run()
        .then(failedCount => {
            console.log('Error: ', failedCount);
        })
        .catch(error => {
            console.log('Error: ', error);
        });

        //return testcafe.createBrowserConnection();
    })`

**Comment by miherlosev** [comment]
You are using the old TestCafe version. The 'Recording Video' feature appeared in the version older than `0.22.0`. 
The latest TestCafe version (`1.1.2`) exactly includes this feature.

**Comment by Esteban26** [comment]
thanks @miherlosev  I'll try that version.

**Comment by Esteban26** [comment]
@miherlosev I'm facing another issue, the application we are testing to get the videos contains a threesixty animation... The problem we noticed is the video shows the 360 animation paused, I tried by increasing the -r option (fps) for the ffmpeg library option but I got the same result... I also noticed the result video seems to be created with multiple videos joined, is it possible to get an smoothest animation on the videos?

**Comment by Esteban26** [comment]
@miherlosev @AndreyBelym 
I noticed video is created with screenshots at  process.js file / _capture() method... I see there is a while loop.. I think there is where you get the frames to create the video... but what I see it is delaying a lot to get the next frame, my test case delays only 5 seconds to complete the 360 rotation and the video only gets 6/7 images to be created... I attached the file with the resultant video

https://github.com/DevExpress/testcafe/commit/daa552b48863249036a6e435e3b6317dbba85669#diff-981865284639c0025e8ea7f5551b9aee

**Comment by Farfurix** [comment]
@Esteban26 

Hello.

If you faced another issue, please open a [new Bug Report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). I couldn't download your video file. Please make it public (without any authorization requests) and attach to a new Bug Report.

**Comment by Esteban26** [comment]
I think this issue should not be closed since Testcafe its getting the video frames with its screenshot module, so it is a problem with test cafe because there are not enough frames to complete an smoother animation. Doesn't make sense for me and maybe for somebody else solve the issue by  increasing the animation time execution because in that case I won't test what I need...
